# Cloud Build configuration for Frontend (Next.js)
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/city-platform-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/city-platform-frontend:latest'
      - './frontend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/city-platform-frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/city-platform-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'city-platform-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/city-platform-frontend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Substitutions
substitutions:
  _REGION: 'europe-west1'  # Change to your preferred region

# Images to be pushed to the Container Registry
images:
  - 'gcr.io/$PROJECT_ID/city-platform-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/city-platform-frontend:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

